server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
spring:
  profiles: common
  tomcat:
    uri-encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/song_mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: song1997@
  redis:
    host: 192.168.0.100
    port: 6379
    database: 0
    password: 150313
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
    timeout: 10000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://192.168.0.100:9000
  accessKey: song
  secretKey: songzewei
  bucketName: minio-data
pagehelper:
  helper-dialect: mysql
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  type-aliases-package: com.song.common.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml